model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 20
    feature_size: 1
    n_layer_enc: 3
    n_layer_dec: 2
    d_model: 64  # 4 X 16
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 5000
  results_folder: ./Checkpoints_aluminium_prices
  gradient_accumulate_every: 2
  save_cycle: 500  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10

  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 4000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500
      verbose: false

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: aluminium_prices
      proportion: 0.9  # Set to rate < 1 if training conditional generation
      data_root: ./diffusion_model/Data/datasets/aluminium_prices.csv
      window: 20  # seq_length
      save2npy: true
      neg_one_to_one: true
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: aluminium_prices
      proportion: 0.9  # rate
      data_root: ./diffusion_model/Data/datasets/aluminium_prices.csv
      window: 20  # seq_length
      save2npy: true
      neg_one_to_one: true
      seed: 123
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 64
  sample_size: 256
  shuffle: true
